# Generated by Django 4.1.7 on 2023-03-26 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("michalowa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumuser",
            name="user_pictrue",
            field=models.ImageField(blank=True, null=True, upload_to="images/users"),
        ),
        migrations.AddField(
            model_name="post",
            name="subject_pictrue",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/subject_pic"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="likes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="michalowa.forumuser",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="subject_pictrue",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/subject_pic"
            ),
        ),
    ]
