# Generated by Django 4.1.7 on 2023-03-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("michalowa", "0002_forumuser_user_pictrue_post_subject_pictrue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumuser",
            name="user_pictrue",
            field=models.ImageField(
                blank=True,
                default="images/users/default.jpg",
                null=True,
                upload_to="images/users",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="subject_pictrue",
            field=models.ImageField(
                blank=True,
                default="images/subject_pic/kotki.png",
                null=True,
                upload_to="images/subject_pic",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_pictrue",
            field=models.ImageField(
                blank=True,
                default="images/subject_pic/kotki.png",
                null=True,
                upload_to="images/subject_pic",
            ),
        ),
    ]
