# Generated by Django 4.1.7 on 2023-03-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("michalowa", "0003_alter_forumuser_user_pictrue_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="likes",
        ),
        migrations.AddField(
            model_name="subject",
            name="likes",
            field=models.ManyToManyField(
                null=True, related_name="likes", to="michalowa.forumuser"
            ),
        ),
    ]
